### PR TITLE
Clarify API key instructions

### PR DESCRIPTION
**Pull request by futurejohn**
The original instructions were a little ambiguous and I had to do some trial and error to get it working for me.

### CODE REVIEW

**Comment by futurejohn** [comment]
I also tested it with my Pixel Watch so I added it to the compatibility list. Works nearly flawlessly in most cases, with some occasional stuttering and a few crashes. Scrolling with the crown goes way too fast and vibrates the watch too much, almost like it's doing too many 'clicks' for each step.

**Comment by tdrkDev** [comment]
Hello, sorry for the late reply, thanks for your cooperation! Will be merged after major restructuring and rewriting.

**Comment by futurejohn** [comment]
No worries, thanks! Is there anything you'd like me to test?

**Comment by skdubg** [comment]
Version 0.4.2 is working on Fossil/Skagen/Michael Kors Gen6 smartwatches with WearOS 3 too
they could be added to the compatibility list

**Comment by tdrkDev** [comment]
Closed due to deprecation of the `legacy` branch. `main` branch's README is still WIP.

**Pull request closed without merging**
